// Порядок и ключи категорий — должны совпадать с порядком t.cats в Home.jsx
export const CATEGORY_KEYS = [
  "auto", "realestate", "electronics", "jobs", "home_goods",
  "clothes", "kids", "services", "hobby", "animals", "business", "free",
];

// Полный каталог: категория -> подкатегории -> бренды/типы -> модели
// hasBrands: true означает что у подкатегории есть бренды/типы для дальнейшего выбора
// Если у бренда models пустой или содержит только 1 общую запись - клик сразу ведёт к объявлениям
export const CATALOG = {
  auto: {
    name: "Транспорт",
    icon: "🚗",
    desc: "Автомобили, мотоциклы, грузовики и запчасти",
    count: "111K+",
    subcats: [
      {
        id: "passenger", name: "Легковые", icon: "🚗", hasBrands: true,
        brands: [
          { id: "acura", name: "Acura", models: ["Все модели"] },
          { id: "aiways", name: "Aiways", models: ["Все модели"] },
          { id: "arcfox", name: "Arcfox", models: ["Все модели"] },
          { id: "alfa_romeo", name: "Alfa Romeo", models: ["Giulia", "Stelvio", "Другие модели"] },
          { id: "audi", name: "Audi", models: ["A4", "A6", "Q5", "Q7", "A3", "Другие модели"] },
          { id: "avatr", name: "Avatr", models: ["Все модели"] },
          { id: "baic", name: "BAIC", models: ["Все модели"] },
          { id: "baw", name: "BAW", models: ["Все модели"] },
          { id: "beijing", name: "Beijing", models: ["Все модели"] },
          { id: "bentley", name: "Bentley", models: ["Continental", "Bentayga", "Другие модели"] },
          { id: "bestune", name: "Bestune", models: ["T77", "T99", "Другие модели"] },
          { id: "brilliance", name: "Brilliance", models: ["Все модели"] },
          { id: "bmw", name: "BMW", models: ["3 Series", "5 Series", "X5", "X3", "7 Series", "X1", "X6", "Другие модели"] },
          { id: "buick", name: "Buick", models: ["Encore", "Envision", "Другие модели"] },
          { id: "byd", name: "BYD", models: ["Song Plus", "Atto 3", "Han", "Tang", "Qin Plus", "Seal", "Другие модели"] },
          { id: "cadillac", name: "Cadillac", models: ["Escalade", "XT5", "Другие модели"] },
          { id: "changan", name: "Changan", models: ["CS35", "CS55", "CS75", "Alsvin", "UNI-T", "Другие модели"] },
          { id: "changhe", name: "Changhe", models: ["Все модели"] },
          { id: "chevrolet", name: "Chevrolet", models: ["Cobalt", "Spark", "Nexia", "Malibu", "Lacetti", "Captiva", "Tracker", "Другие модели"] },
          { id: "chery", name: "Chery", models: ["Tiggo 7", "Tiggo 8", "Arrizo 5", "Другие модели"] },
          { id: "chrysler", name: "Chrysler", models: ["Все модели"] },
          { id: "citroen", name: "Citroen", models: ["C4", "C5", "Другие модели"] },
          { id: "daewoo", name: "Daewoo", models: ["Nexia", "Matiz", "Gentra", "Cobalt", "Другие модели"] },
          { id: "dodge", name: "Dodge", models: ["Charger", "Challenger", "Другие модели"] },
          { id: "dongfeng", name: "Dongfeng", models: ["AX7", "Fengshen", "Другие модели"] },
          { id: "enovate", name: "Enovate", models: ["Все модели"] },
          { id: "faw", name: "FAW", models: ["Bestune T77", "Другие модели"] },
          { id: "fiat", name: "Fiat", models: ["Все модели"] },
          { id: "foton", name: "Foton", models: ["Все модели"] },
          { id: "ford", name: "Ford", models: ["Focus", "Explorer", "Mustang", "Kuga", "Другие модели"] },
          { id: "gac", name: "GAC", models: ["GS3", "GS8", "Empow", "Aion", "Другие модели"] },
          { id: "geely", name: "Geely", models: ["Coolray", "Atlas", "Emgrand", "Monjaro", "Другие модели"] },
          { id: "gmc", name: "GMC", models: ["Yukon", "Sierra", "Другие модели"] },
          { id: "gwm", name: "GWM", models: ["Все модели"] },
          { id: "haval", name: "Haval", models: ["Jolion", "F7", "H6", "Dargo", "Другие модели"] },
          { id: "hiphi", name: "HiPhi", models: ["Все модели"] },
          { id: "hummer", name: "Hummer", models: ["H2", "H3", "EV", "Другие модели"] },
          { id: "honda", name: "Honda", models: ["Civic", "Accord", "CR-V", "Pilot", "Fit", "Другие модели"] },
          { id: "hongqi", name: "Hongqi", models: ["H5", "H9", "E-HS9", "Другие модели"] },
          { id: "huawei", name: "Huawei", models: ["Все модели"] },
          { id: "hyundai", name: "Hyundai", models: ["Elantra", "Tucson", "Sonata", "Santa Fe", "Accent", "Solaris", "Creta", "Palisade", "i30", "Ioniq 6", "Tucson N Line", "Santa Cruz", "Ioniq 5 (2026)", "Ioniq 6", "Tucson (2026)", "Elantra (2026)", "Inster", "Другие модели"] },
          { id: "infiniti", name: "Infiniti", models: ["QX60", "Q50", "FX35", "Другие модели"] },
          { id: "iran_khodro", name: "Iran Khodro", models: ["Все модели"] },
          { id: "jac", name: "JAC", models: ["JS4", "JS6", "S3", "Другие модели"] },
          { id: "jaguar", name: "Jaguar", models: ["F-Pace", "XE", "XF", "Другие модели"] },
          { id: "jeep", name: "Jeep", models: ["Wrangler", "Grand Cherokee", "Compass", "Другие модели"] },
          { id: "jetour", name: "Jetour", models: ["Все модели"] },
          { id: "kia", name: "Kia", models: ["K5", "Sportage", "Rio", "Sorento", "Cerato", "Sephia", "Soul", "Optima", "Sportage (2026)", "EV6", "EV3", "K4", "Niro", "Другие модели"] },
          { id: "lada_ваз", name: "Lada (ВАЗ)", models: ["Granta", "Vesta", "Niva", "Largus", "2107", "2114", "Priora", "XRAY", "Другие модели"] },
          { id: "lamborghini", name: "Lamborghini", models: ["Все модели"] },
          { id: "land_rover", name: "Land Rover", models: ["Range Rover", "Discovery", "Defender", "Evoque", "Другие модели"] },
          { id: "landwind", name: "Landwind", models: ["Все модели"] },
          { id: "leapmotor", name: "Leapmotor", models: ["Все модели"] },
          { id: "leopaard", name: "Leopaard", models: ["Все модели"] },
          { id: "lexus", name: "Lexus", models: ["RX", "ES", "LX", "NX", "GX", "LX570", "Другие модели"] },
          { id: "lifan", name: "Lifan", models: ["Все модели"] },
          { id: "li_auto_lixiang", name: "Li Auto (LiXiang)", models: ["Все модели"] },
          { id: "lynk_and_co", name: "Lynk & Co", models: ["Все модели"] },
          { id: "marvel", name: "Marvel", models: ["Все модели"] },
          { id: "mazda", name: "Mazda", models: ["CX-5", "Mazda3", "Mazda6", "CX-9", "Другие модели"] },
          { id: "mercedes_benz", name: "Mercedes-Benz", models: ["C-Class", "E-Class", "GLE", "GLC", "S-Class", "Sprinter", "Vito", "Другие модели"] },
          { id: "mini", name: "Mini", models: ["Cooper", "Countryman", "Другие модели"] },
          { id: "mitsubishi", name: "Mitsubishi", models: ["Outlander", "Pajero", "ASX", "Lancer", "Другие модели"] },
          { id: "neta", name: "Neta", models: ["Все модели"] },
          { id: "nissan", name: "Nissan", models: ["X-Trail", "Qashqai", "Almera", "Teana", "Patrol", "Tiida", "Note", "Murano", "Другие модели"] },
          { id: "opel", name: "Opel", models: ["Astra", "Corsa", "Insignia", "Другие модели"] },
          { id: "peugeot", name: "Peugeot", models: ["308", "3008", "408", "Другие модели"] },
          { id: "porsche", name: "Porsche", models: ["Cayenne", "Macan", "Panamera", "Другие модели"] },
          { id: "radar", name: "Radar", models: ["Все модели"] },
          { id: "ravon", name: "Ravon", models: ["Все модели"] },
          { id: "renault", name: "Renault", models: ["Duster", "Logan", "Sandero", "Arkana", "Другие модели"] },
          { id: "rising_auto", name: "Rising Auto", models: ["Все модели"] },
          { id: "roewe", name: "Roewe", models: ["RX5", "i5", "Другие модели"] },
          { id: "rolls_royce", name: "Rolls-Royce", models: ["Phantom", "Ghost", "Cullinan", "Другие модели"] },
          { id: "rover", name: "Rover", models: ["Все модели"] },
          { id: "rox", name: "Rox", models: ["Все модели"] },
          { id: "saab", name: "Saab", models: ["Все модели"] },
          { id: "saturn", name: "Saturn", models: ["Все модели"] },
          { id: "shuanghuan", name: "Shuanghuan", models: ["Все модели"] },
          { id: "skoda", name: "Skoda", models: ["Octavia", "Rapid", "Superb", "Kodiaq", "Другие модели"] },
          { id: "skyworth", name: "Skyworth", models: ["Все модели"] },
          { id: "smart", name: "Smart", models: ["Все модели"] },
          { id: "soueast", name: "Soueast", models: ["Все модели"] },
          { id: "subaru", name: "Subaru", models: ["Forester", "Outback", "XV", "Другие модели"] },
          { id: "ssang_yong", name: "Ssang Yong", models: ["Korando", "Rexton", "Tivoli", "Другие модели"] },
          { id: "suzuki", name: "Suzuki", models: ["Vitara", "Swift", "Jimny", "Другие модели"] },
          { id: "tank", name: "Tank", models: ["Все модели"] },
          { id: "tesla", name: "Tesla", models: ["Model 3", "Model Y", "Model S", "Другие модели"] },
          { id: "toyota", name: "Toyota", models: ["Corolla", "Camry", "RAV4", "Land Cruiser", "Land Cruiser Prado", "Voxy", "Prius", "Highlander", "Avensis", "Yaris", "Hilux", "Fortuner", "Alphard", "Velfire", "GR86", "Crown", "bZ4X", "RAV4 Hybrid (2026)", "Land Cruiser 300", "Camry (2026)", "Corolla Cross", "Другие модели"] },
          { id: "volkswagen", name: "Volkswagen", models: ["Tiguan", "Passat", "Golf", "Polo", "Jetta", "Touareg", "Другие модели"] },
          { id: "volvo", name: "Volvo", models: ["XC60", "XC90", "S60", "Другие модели"] },
          { id: "voyah", name: "Voyah", models: ["Все модели"] },
          { id: "weltmeister", name: "Weltmeister", models: ["Все модели"] },
          { id: "wey", name: "WEY", models: ["Все модели"] },
          { id: "wuling", name: "Wuling", models: ["Hongguang Mini EV", "Другие модели"] },
          { id: "xiaomi", name: "Xiaomi", models: ["SU7", "Другие модели"] },
          { id: "xpeng", name: "Xpeng", models: ["Все модели"] },
          { id: "zeekr", name: "Zeekr", models: ["001", "009", "Другие модели"] },
          { id: "zotye", name: "Zotye", models: ["Все модели"] },
          { id: "газ", name: "ГАЗ", models: ["Волга", "21", "24", "Другие модели"] },
          { id: "заз", name: "ЗАЗ", models: ["Все модели"] },
          { id: "иж", name: "ИЖ", models: ["Все модели"] },
          { id: "москвич", name: "Москвич", models: ["412", "2141", "3", "Другие модели"] },
          { id: "уаз", name: "УАЗ", models: ["Patriot", "Hunter", "469", "Другие модели"] },
          { id: "другие_марки", name: "Другие марки", models: ["Все модели"] },
        ],
      },
      {
        id: "truck", name: "Грузовики", icon: "🚚", hasBrands: true,
        brands: [
          { id: "kamaz", name: "КамАЗ", models: ["5320", "65115", "43118", "5410", "Другие модели"] },
          { id: "zil", name: "ЗиЛ", models: ["130", "131", "5301 Бычок", "Другие модели"] },
          { id: "gaz_truck", name: "ГАЗ (Газель)", models: ["Газель Next", "Газель Бизнес", "ГАЗ-53", "Другие модели"] },
          { id: "isuzu", name: "Isuzu", models: ["NPR", "Elf", "Forward", "Giga", "Другие модели"] },
          { id: "hyundai_t", name: "Hyundai", models: ["HD78", "HD120", "Mighty", "HD65", "Другие модели"] },
          { id: "man", name: "MAN", models: ["TGS", "TGX", "TGM", "Другие модели"] },
          { id: "volvo_t", name: "Volvo Trucks", models: ["FH", "FM", "FMX", "Другие модели"] },
          { id: "scania", name: "Scania", models: ["R-series", "P-series", "G-series", "Другие модели"] },
          { id: "daf", name: "DAF", models: ["XF", "CF", "LF", "Другие модели"] },
          { id: "mercedes_t", name: "Mercedes-Benz", models: ["Actros", "Atego", "Другие модели"] },
        ],
      },
      {
        id: "moto", name: "Мотоциклы", icon: "🏍️", hasBrands: true,
        brands: [
          { id: "honda_m", name: "Honda", models: ["CB400", "CBR600", "Africa Twin", "CB500", "Другие модели"] },
          { id: "yamaha", name: "Yamaha", models: ["MT-07", "R1", "YBR125", "Aerox", "Другие модели"] },
          { id: "racer", name: "Racer", models: ["Magnum", "Panther", "Hunter", "Другие модели"] },
          { id: "irbis", name: "Irbis", models: ["TTR", "Z150", "Другие модели"] },
          { id: "suzuki_m", name: "Suzuki", models: ["GSX-R", "Boulevard", "Другие модели"] },
        ],
      },
      { id: "parts", name: "Запчасти", icon: "🔧", hasBrands: false },
      { id: "tires", name: "Шины и диски", icon: "🛞", hasBrands: false },
    ],
  },

  electronics: {
    name: "Электроника",
    icon: "📱",
    desc: "Телефоны, ноутбуки, планшеты и аксессуары",
    count: "28K+",
    subcats: [
      {
        id: "phones", name: "Смартфоны", icon: "📱", hasBrands: true,
        brands: [
          { id: "apple", name: "Apple", models: ["iPhone SE (2020)", "iPhone SE (2022)", "iPhone SE (2024)", "iPhone 11", "iPhone 11 Pro", "iPhone 12", "iPhone 12 Pro", "iPhone 13", "iPhone 13 Pro", "iPhone 13 Pro Max", "iPhone 14", "iPhone 14 Pro", "iPhone 14 Pro Max", "iPhone 15", "iPhone 15 Plus", "iPhone 15 Pro", "iPhone 15 Pro Max", "iPhone 16", "iPhone 16 Plus", "iPhone 16 Pro", "iPhone 16 Pro Max", "iPhone 16e", "iPhone 17", "iPhone 17 Pro", "iPhone 17 Pro Max", "iPhone Air", "iPhone 17e", "Другие модели"] },
          { id: "samsung", name: "Samsung", models: ["Galaxy A05", "Galaxy A15", "Galaxy A35", "Galaxy A55", "Galaxy A14", "Galaxy A54", "Galaxy S21", "Galaxy S21 Ultra", "Galaxy S22", "Galaxy S22 Ultra", "Galaxy S23", "Galaxy S23 Ultra", "Galaxy S24", "Galaxy S24 Ultra", "Galaxy S25", "Galaxy S25 Ultra", "Galaxy Z Flip 5", "Galaxy Z Fold 5", "Galaxy Z Fold 6", "Galaxy S26", "Galaxy S26+", "Galaxy S26 Ultra", "Galaxy A16", "Galaxy A26", "Galaxy Z Flip 6", "Другие модели"] },
          { id: "xiaomi", name: "Xiaomi", models: ["Redmi 12", "Redmi 12C", "Redmi 13", "Redmi 13C", "Redmi Note 12", "Redmi Note 13", "Redmi Note 14", "Redmi Note 14 Pro", "Xiaomi 13", "Xiaomi 14", "Xiaomi 14 Ultra", "Poco X6", "Poco X6 Pro", "Poco M6", "Poco F6", "Poco F7", "Xiaomi 15", "Xiaomi 15 Ultra", "Redmi Note 14 Pro+", "Другие модели"] },
          { id: "vivo", name: "Vivo", models: ["Y18", "Y28", "Y36", "Y38", "Y100", "V27", "V29", "V30", "V40", "X100", "X100 Ultra", "X200", "X200 Pro", "X300", "X300 Pro", "V50", "Y200", "Другие модели"] },
          { id: "oppo", name: "Oppo", models: ["A78", "Reno 10", "A98", "Find X6", "Find X8", "Reno 13", "A5 Pro", "Другие модели"] },
          { id: "honor", name: "Honor", models: ["X7", "X9", "Magic 6", "90", "Magic 7", "Magic 7 Pro", "X9c", "Другие модели"] },
          { id: "huawei", name: "Huawei", models: ["Nova 10", "Nova 11", "Nova 12", "Nova 13", "P50", "P60", "Mate 50", "Mate 60", "Mate 70", "Mate 70 Pro", "Pura 80", "Nova 14", "Другие модели"] },
          { id: "realme", name: "Realme", models: ["C55", "11 Pro", "GT 5", "Другие модели"] },
          { id: "infinix", name: "Infinix", models: ["Hot 40", "Note 30", "Zero 30", "Другие модели"] },
          { id: "tecno", name: "Tecno", models: ["Spark 10", "Camon 20", "Pova 5", "Другие модели"] },
          { id: "nokia", name: "Nokia", models: ["G42", "C32", "105 (кнопочный)", "Другие модели"] },
          { id: "lg_phone", name: "LG", models: ["G8", "V60", "Wing", "K52", "Другие модели"] },
          { id: "sony", name: "Sony", models: ["Xperia 1", "Xperia 5", "Xperia 10", "Другие модели"] },
          { id: "google", name: "Google Pixel", models: ["Pixel 6", "Pixel 7", "Pixel 8", "Pixel 8 Pro", "Pixel 9", "Pixel 9 Pro", "Pixel 9 Pro XL", "Pixel 9a", "Другие модели"] },
        ],
      },
      {
        id: "laptops", name: "Ноутбуки", icon: "💻", hasBrands: true,
        brands: [
          { id: "apple_mb", name: "Apple MacBook", models: ["Air M1", "Air M2", "Air M3", "Pro 14 M3", "Pro 16 M3", "Другие модели"] },
          { id: "lenovo", name: "Lenovo", models: ["IdeaPad 3", "IdeaPad 5", "ThinkPad X1", "Legion 5", "Другие модели"] },
          { id: "hp", name: "HP", models: ["Pavilion", "EliteBook", "Omen", "Probook", "Другие модели"] },
          { id: "asus", name: "Asus", models: ["VivoBook", "ZenBook", "ROG Strix", "TUF Gaming", "Другие модели"] },
          { id: "dell", name: "Dell", models: ["XPS 13", "Inspiron", "Latitude", "Vostro", "Другие модели"] },
          { id: "acer", name: "Acer", models: ["Aspire", "Nitro 5", "Swift", "Другие модели"] },
          { id: "msi", name: "MSI", models: ["Modern 14", "Katana", "Stealth", "Другие модели"] },
        ],
      },
      {
        id: "tablets", name: "Планшеты", icon: "📲", hasBrands: true,
        brands: [
          { id: "apple_ip", name: "Apple iPad", models: ["iPad 9", "iPad 10", "iPad Air", "iPad Pro 11", "iPad Pro 12.9", "Другие модели"] },
          { id: "samsung_t", name: "Samsung", models: ["Tab A9", "Tab S9", "Tab S9 Ultra", "Другие модели"] },
          { id: "huawei_t", name: "Huawei", models: ["MatePad 11", "MatePad Pro", "Другие модели"] },
        ],
      },
      {
        id: "tv", name: "Телевизоры", icon: "📺", hasBrands: true,
        brands: [
          { id: "samsung_tv", name: "Samsung", models: ["43\" Smart", "55\" QLED", "65\" QLED", "75\" Neo QLED", "Другие модели"] },
          { id: "lg_tv", name: "LG", models: ["43\" Smart", "55\" OLED", "65\" OLED", "Другие модели"] },
          { id: "artel", name: "Artel", models: ["32\" Smart", "43\" Smart", "55\" Smart", "Другие модели"] },
          { id: "xiaomi_tv", name: "Xiaomi", models: ["43\" Mi TV", "55\" Mi TV", "Другие модели"] },
          { id: "sony_tv", name: "Sony", models: ["55\" Bravia", "65\" Bravia", "Другие модели"] },
        ],
      },
      { id: "accessories", name: "Аксессуары", icon: "🎧", hasBrands: false },
    ],
  },

  realestate: {
    name: "Недвижимость", icon: "🏠", desc: "Квартиры, дома и земельные участки", count: "65K+",
    subcats: [
      { id: "flat_sale", name: "Квартиры — продажа", icon: "🏢", hasBrands: false },
      { id: "flat_rent", name: "Квартиры — аренда", icon: "🔑", hasBrands: false },
      { id: "house", name: "Дома", icon: "🏡", hasBrands: false },
      { id: "land", name: "Участки", icon: "🌳", hasBrands: false },
      { id: "commercial", name: "Коммерческая", icon: "🏬", hasBrands: false },
    ],
  },

  jobs: {
    name: "Работа", icon: "💼", desc: "Вакансии и резюме", count: "42K+",
    subcats: [
      { id: "vacancy", name: "Вакансии", icon: "📋", hasBrands: false },
      { id: "resume", name: "Резюме", icon: "📄", hasBrands: false },
    ],
  },

  home_goods: {
    name: "Для дома", icon: "🛋️", desc: "Мебель, техника, интерьер", count: "19K+",
    subcats: [
      { id: "furniture", name: "Мебель", icon: "🛋️", hasBrands: false },
      {
        id: "appliances", name: "Бытовая техника", icon: "🧺", hasBrands: true,
        brands: [
          { id: "samsung_a", name: "Samsung", models: ["Холодильник", "Стиральная машина", "Микроволновка", "Пылесос", "Другие модели"] },
          { id: "lg_a", name: "LG", models: ["Холодильник", "Стиральная машина", "Кондиционер", "Другие модели"] },
          { id: "artel_a", name: "Artel", models: ["Холодильник", "Стиральная машина", "Плита", "Другие модели"] },
          { id: "bosch", name: "Bosch", models: ["Стиральная машина", "Посудомойка", "Холодильник", "Другие модели"] },
          { id: "indesit", name: "Indesit", models: ["Стиральная машина", "Холодильник", "Духовка", "Другие модели"] },
        ],
      },
      { id: "decor", name: "Интерьер и декор", icon: "🖼️", hasBrands: false },
    ],
  },

  clothes: {
    name: "Одежда", icon: "👗", desc: "Одежда и обувь", count: "15K+",
    subcats: [
      {
        id: "women", name: "Женская одежда", icon: "👗", hasBrands: true,
        brands: [
          { id: "w_dresses", name: "Платья", models: [] },
          { id: "w_outerwear", name: "Верхняя одежда (куртки, пальто)", models: [] },
          { id: "w_sneakers", name: "Кроссовки и обувь", models: [] },
          { id: "w_sport", name: "Спортивная одежда", models: [] },
          { id: "w_jeans", name: "Джинсы и брюки", models: [] },
          { id: "w_blouses", name: "Блузки и рубашки", models: [] },
          { id: "w_skirts", name: "Юбки", models: [] },
          { id: "w_underwear", name: "Бельё", models: [] },
        ],
      },
      {
        id: "men", name: "Мужская одежда", icon: "👔", hasBrands: true,
        brands: [
          { id: "m_outerwear", name: "Верхняя одежда (куртки, пальто)", models: [] },
          { id: "m_sneakers", name: "Кроссовки и обувь", models: [] },
          { id: "m_sport", name: "Спортивная одежда", models: [] },
          { id: "m_shirts", name: "Рубашки и футболки", models: [] },
          { id: "m_jeans", name: "Джинсы и брюки", models: [] },
          { id: "m_suits", name: "Костюмы", models: [] },
          { id: "m_underwear", name: "Бельё", models: [] },
        ],
      },
      { id: "kids_clothes", name: "Детская одежда", icon: "👶", hasBrands: false },
      { id: "shoes", name: "Обувь", icon: "👟", hasBrands: false },
    ],
  },

  kids: {
    name: "Детский мир", icon: "🧸", desc: "Товары для детей", count: "12K+",
    subcats: [
      { id: "toys", name: "Игрушки", icon: "🧸", hasBrands: false },
      { id: "strollers", name: "Коляски", icon: "🍼", hasBrands: false },
      { id: "kids_furniture", name: "Детская мебель", icon: "🛏️", hasBrands: false },
    ],
  },

  services: {
    name: "Услуги", icon: "🔧", desc: "Все виды услуг", count: "31K+",
    subcats: [
      { id: "repair", name: "Ремонт и строительство", icon: "🔨", hasBrands: false },
      { id: "beauty", name: "Красота и здоровье", icon: "💅", hasBrands: false },
      { id: "education", name: "Обучение", icon: "📚", hasBrands: false },
      { id: "transport_serv", name: "Грузоперевозки", icon: "🚛", hasBrands: false },
    ],
  },

  hobby: {
    name: "Хобби", icon: "⚽", desc: "Спорт и хобби", count: "8K+",
    subcats: [
      { id: "sport", name: "Спортивные товары", icon: "⚽", hasBrands: false },
      { id: "books", name: "Книги", icon: "📖", hasBrands: false },
      { id: "music", name: "Музыкальные инструменты", icon: "🎸", hasBrands: false },
    ],
  },

  animals: {
    name: "Животные", icon: "🐾", desc: "Питомцы и товары для животных", count: "5K+",
    subcats: [
      { id: "pets", name: "Питомцы", icon: "🐶", hasBrands: false },
      { id: "pet_goods", name: "Товары для животных", icon: "🦴", hasBrands: false },
    ],
  },

  business: {
    name: "Бизнес", icon: "📊", desc: "Готовый бизнес и оборудование", count: "7K+",
    subcats: [
      { id: "ready_business", name: "Готовый бизнес", icon: "🏪", hasBrands: false },
      { id: "equipment", name: "Оборудование", icon: "⚙️", hasBrands: false },
    ],
  },

  free: {
    name: "Отдам даром", icon: "🎁", desc: "Бесплатные вещи", count: "3K+", subcats: null,
  },
};
